# Generated by Django 5.0.7 on 2024-07-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_stripecustomer_subscriptionplanid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='subscriptionPlanId',
        ),
    ]
